version: "3"

services:
  identity_service:
    build: ./identity-service
    image: cc-dev-identity-service:1.0.0
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DB: $MYSQL_DB
    volumes:
      - ./identity-service:/usr/src/app/identity-service
    depends_on:
      - db
    links:
      - db
    ports:
      - 5051:80

  message_persistence_service:
    build: ./message-persistence-service
    image: cc-dev-message-persistence-service:1.0.0
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DB: $MYSQL_DB
    depends_on:
      - db
    links:
      - db
    ports:
      - 5052:80

  websocket_service:
    build: ./websocket-service
    image: cc-dev-websocket-service:1.0.0
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_DB_NUM: 0
      REDIS_SIDEKIQ_DB_NUM: 10
    volumes:
      - ./websocket-service:/usr/src/app
    links:
      - redis
      - identity_service
    depends_on:
      - redis
      - identity_service
    ports:
      - 5053:80


  redis:
    image: redis:4.0-alpine
    ports:
      - 6380:6379
    command: ['redis-server']
    volumes:
      - redis-data:/data

  kafka_service:
    build: ./kafka-service
    image: cc-dev-kafka-service:1.0.0
    volumes:
      - ./kafka-service:/usr/src/app/kafka-service
    ports:
      - 5054:80

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'devpass'
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    ports:
      - 3380:3306
    expose:
      - 3380
#    volumes:
#      - "./db/data:/var/lib/mysql"
#      - "./db/initdb:/docker-entrypoint-initdb.d/:ro"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080

volumes:
  redis-data:
  db-data:
